Wdp220701-38  ProductPopup
odevpl/wdp-2207-01 pull request #46
Opened 2022-07-21 18:27 UTC by DmkMrw

2022-07-22 14:08 UTC, milosz7 requested changes

2022-07-22 14:08 UTC, milosz7 commented on src/components/features/ProductPopup/ProductPopup.js
> +const ProductPopup = props => {
Could you please destructure props? I thunk it will increase code readability.

2022-07-22 14:08 UTC, milosz7 commented on src/components/common/ProductBox/ProductBox.js
> +          text={'aaaaaaaaaaaaaaaa'}
I do not see any use cases for this prop in the code - is it necessary?

2022-07-22 14:08 UTC, milosz7 commented on src/components/features/ProductPopup/ProductPopup.module.scss
> +@import "../../../styles/settings.scss";
I think that the popup is a little bit too wide what makes it really spread out - those big spaces in between the lines of text make it stand out from the original page design.

2022-07-22 14:09 UTC, milosz7 commented on src/components/common/ProductBox/ProductBox.js
> +          text={'aaaaaaaaaaaaaaaa'}
Typescript would yell :D

2022-07-22 16:56 UTC, DmkMrw commented on src/components/common/ProductBox/ProductBox.js
> +          text={'aaaaaaaaaaaaaaaa'}
watchful :D

2022-07-22 17:12 UTC, DmkMrw commented
Okay, I fixed problems that you requested. Could you check it again?

2022-07-25 10:39 UTC, milosz7 approved these changes

2022-07-25 10:39 UTC, merged